"""Publish AI review results to workflow logs and the GitHub step summary."""

import argparse
import json
import logging
import os
import sys
from pathlib import Path
from typing import Any

from review.utils import mask_secrets, setup_logging

logger = logging.getLogger("review.ci.publish")

# Format the review summary
def format_review_summary(payload: dict[str, Any]) -> str:
    decision = str(payload.get("decision", "FAIL")).upper()
    icon = "[PASS]" if decision == "PASS" else "[FAIL]"
    score = payload.get("score", "n/a")
    summary = mask_secrets(str(payload.get("summary", "")))
    comments = payload.get("comments") or []

    lines = [
        "## AI Code Review",
        "",
        f"**Decision:** {icon} `{decision}`",
        f"**Score:** {score}",
        "",
        f"**Summary:** {summary}",
        "",
    ]
    if payload.get("infrastructure_failure"):
        lines.extend(
            [
                "> This was an **infrastructure failure** (API/key/schema/timeout), "
                "not only a code-quality FAIL. The pipeline failed closed.",
                "",
            ]
        )
    if comments:
        lines.append("### Findings")
        lines.append("")
        for item in comments:
            lines.append(f"- {mask_secrets(str(item))}")
        lines.append("")
    lines.append("_Generated by `ai-review` workflow using Groq._")
    return "\n".join(lines)

# Parse command line arguments
def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Publish AI review to logs and step summary")
    parser.add_argument(
        "--result-file",
        type=Path,
        default=Path(os.environ.get("REVIEW_RESULT_FILE", "artifacts/review_result.json")),
    )
    return parser.parse_args(argv)

# Main function to publish the AI review
def main(argv: list[str] | None = None) -> int:
    setup_logging(os.environ.get("LOG_LEVEL", "INFO"))
    args = parse_args(argv)

    if not args.result_file.is_file():
        logger.error("Result file not found: %s", args.result_file)
        return 1

    payload = json.loads(args.result_file.read_text(encoding="utf-8"))
    body = format_review_summary(payload)
    print(body)

    summary_file = os.environ.get("GITHUB_STEP_SUMMARY")
    if summary_file:
        with Path(summary_file).open("a", encoding="utf-8") as handle:
            handle.write("\n### AI review feedback\n\n")
            handle.write(body)
            handle.write("\n")

    return 0


if __name__ == "__main__":
    sys.exit(main())
